### ISSUE TITLE
Cannot import v2.0.0

### ISSUE THREAD

**Issue by srebhan** [antchfx/jsonquery#10]
When trying to update to v2.0.0, to get the native value update, the command fails with

```shell
> go get -u github.com/antchfx/jsonquery@v2.0.0
go: github.com/antchfx/jsonquery@v2.0.0: invalid version: module contains a go.mod file, so module path must match major version ("github.com/antchfx/jsonquery/v2")
```

I guess you need to update the module path in `go.mod`!?

**Comment by zhengchun** [comment]
@srebhan , Sorrty about this problem.  I don't known release new major version 2.0 needs to compatible with the previous version before reading https://go.dev/blog/v2-go-modules， so I decied to rollback to v1.3.0.

**Comment by srebhan** [comment]
@zhengchun I'm fine with having this as 1.3.0. I guess for v2 you also need to update your go.mod file if I read the go guidelines correctly. Closing this as resolved for now.
